VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "SinkRSChange"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit

Public Event onreadystatechange()

'Mark as default member via Tools|Procedure Attributes... dialog.
Public Sub RSChange()
Attribute RSChange.VB_UserMemId = 0
    RaiseEvent onreadystatechange
End Sub
